cloudwu/skynet

lualib/skynet.lua

fork_queue is used in skynet.exit,but declared after it.

varable delcared in closure but used for global

---

lualib/skynet.lua

Though the result is not used, 'debug.traceback' is called when 'succ' is true

remove needless 'debug.traceback' call in assert

---

lualib/snax.lua

remove needless 'string.format' as param of assert, add detail error info for not exist interface.

needless 'string.format', accurate error info

---

examples/config
lualib/snax.lua

1、我们新增了一些辅助函数，会在全局调用，比如说解决重复包含的delayrequire，所以想把snax的G改为可配置的，这样在升级skynet的时候，不需要合并代码
2、修改配置项为 snax_interface_g 你若感觉命名不好，我们在讨论
3、你说的 “只取一次 skynet.getenv, 然后用 if else”，我只写改了只取一次 skynet.getenv，“用 if else”我尝试了一下，感觉太丑了，不符合我对代码的审美观，但是你如果坚持，我也可以改过来

snax 的 G 可配置

---

lualib-src/lua-socket.c
skynet-src/socket_server.c

send_socket里面udp数据成功发送的情况下，不需要再调sp_write；
add_udp_socket里面ns为NULL得return，否则后面有空指针引用

fix:udp and udp_send

---

lualib-src/sproto/sproto.c

malloc newchunk and return directly if sz >= CHUNK_SIZE in pool_alloc
do not replace current chunk if sz >= p->current_used in pool_alloc
more safety checking

sproto optimize

---

lualib/snax/hotfix.lua

If there's no global variable or function used in any interface of a snax service,the upvalue "_ENV" for 'hotfix' is not set. This modify is not  complete, it depend's on the 'collect_uv' method having upvalue '_ENV',maybe other good method to get upvalue index of '_ENV'.

'hotfix' code cannot use '_ENV'

---

lualib-src/lua-netpack.c

'uncomplete' buffer not freed in clear

uncomplete buffer not free

---

lualib/skynet.lua

'response' not released after caller service died, and defined error.

'response' not released

---

service-src/service_gate.c

从check_wsz发送的SKYNET_SOCKET_TYPE_WARNING消息会assert失败，导致coredump

从check_wsz发送的SKYNET_SOCKET_TYPE_WARNING消息会assert失败，导致coredump

---

lualib/dns.lua

Although 'f'  would be closed after collected, maybe it's better to close it clearly

close file handle clearly

---

lualib/snax/loginserver.lua

之前可能是我没有表述清楚，这两个return我猜想是不是手误加上去的，因为之前都没有见过需要在消息处理函数里面return skynet.ret调用的结果，实际去掉后测试也是没有问题的，和是不是两次pcall的调用应该是没有关系的。

loginserver.lua中的launch_slave的lua消息处理函数的return问题

---

lualib-src/lua-seri.c

Lua string object referenced by C pointer from lua_tolstring() was
removed from stack by lua_settop(L,0).
Lua 5.3 Reference Manual says:
> Because Lua has garbage collection, there is no guarantee that the
> pointer returned by lua_tolstring will be valid after the
> corresponding Lua value is removed from the stack.
That is it.
Introduced in commit 9937081854c7b65d0a0557c3630ecbf1d62622d8.

Fix dangling c pointer to lua string value

---

service/debug_console.lua

[:00000009] lua call [0 to :9 : 0 msgsz = 24] error : [31mlua/lualib/skynet.lua:521: lua/lualib/skynet.lua:155: lua/service/debug_console.lua:234: attempt to index a boolean value (local 'cmdline')
stack traceback:
lua/service/debug_console.lua:234: in upvalue 'func'
lua/lualib/skynet.lua:457: in upvalue 'f'
lua/lualib/skynet.lua:109: in function <lua/lualib/skynet.lua:103>
stack traceback:
[C]: in function 'assert'
lua/lualib/skynet.lua:521: in function 'skynet.dispatch_message'[0m

fix a debug_console error

---

3rd/lua/lstring.c

Short strings in lua proto are reused most of the time. The string in SSM may be added by one service and used by other service,  there is no need to call `add_string`,which will call 'new_string' first.

reduce needless 'add_string' call

---

lualib/skynet/remotedebug.lua

这样改过之后可以直接调试使用了gate服务的模块。
因为gate服务注册了socket类型的消息，所以不能和socket模块一块使用；而debug模块只使用到了socket模块的write函数，所以这样修改后对debug的功能并没有影响，但改过之后就可以调试gate服务了。

change socket.write to socketdriver.send

---

lualib/skynet/debug.lua

我们项目增加了一个dbgcmd的指令，主要用于热更新，但在升级skynet版本时，需要记得合并这个差异，感觉挺挫的。
但现有的debug.lua并不利于扩展，于是呢，我想通过给debug.lua增加一个upvalue来解决这个问题。
其实也是解决的挺挫的 :)

给dbgcmd增加扩展性

---

lualib/snax.lua
lualib/snax/interface.lua
service/snaxd.lua

在某些情况下，需要设置snax 服务的info_func, 设置之后就不能方便的获取snaxd 中记录的profile_table了。
于是,增加snax.profile_info 接口
```
snax.profile_info(some_snax_service)
```

add snax.profile_info interface

---

lualib/sharedata/corelib.lua

有同学不小心把sharedata返回的table直接拿来用了。所以给sharedata对象增加了newindex，newindex的时候抛出error，方便排查问题。
麻烦云风看看ok不，thanks

error report on sharedata newindex

---

lualib-src/lua-socket.c
lualib/snax/gateserver.lua
lualib/socket.lua
lualib/socketchannel.lua
skynet-src/skynet_socket.c
skynet-src/skynet_socket.h
skynet-src/socket_server.c
skynet-src/socket_server.h

优化了SOCKET_WARNING机制，超过1M后会在缓存每翻一倍时发送一次waring警告消息 ，之后在缓存又降为0时发送warning 0KB 的消息。
socket发送api返回值现在都是-1失败，0成功。
虚拟机测试时发现sp_wait可能有EINTR错误，添加了处理。
原来send_buffer()中的step4，在低优先队列不为空时会多一次sp_wait可写事件判断，已修改。

optimize SOCKET_WARNING msg

---

skynet-src/malloc_hook.c
skynet-src/skynet_malloc.h

项目中引入使用 cryptopp 库出现崩溃
崩溃原因是 cryptopp 中部分内存使用了 memalign 进行分配，而 skynet 没有 hook 该函数，导致在释放这部分内存时出现越界访问导致程序崩溃
建议将 memalign 加入 malloc hook

hook memalign

---

lualib/skynet/db/redis/cluster.lua

根据test文件中，输入端口号为number类型，此处应该使用d%，否则只format直进来ip，容易造成同一个ip地址的connection丢失。

更正connection丢失的问题

---

skynet-src/skynet_timer.c

clock_gettime had been implemented in macos10.12

using clock_gettime in macos(in macos_10.12 and later)

---

skynet-src/skynet_main.c

The code in skynet_main.c wasn't clearing the struct sigaction before passing it to sigaction().
This meant that we would block a random set of signals while executing the SIGPIPE handler, or jump to the uninitialized __sa_sigaction__ (instead of sa_handler).
Initialize properly as we do in skynet_start.c.

Properly initialize sigaction struct

---

service-src/service_gate.c

service_gate的地址解析用strchr找到第一个':'，并将后续的字符串作为
端口号解析。填ipv6地址"0:0:0:0:0:0:0:0:9999"的时候会出错，现在改成
strrchr，从右面找到的第一个':'

add ipv6 host support to service_gate.c

---

service-src/service_gate.c

单机16核32G，pps 50w，压测 5w 连接，上来只简单的发 ping 包，不能顺利创建 5w 连接，客户端会出现少量连接超时。backlog 改成 128 后，可以顺利创建 5w 连接。
具体原因仍在排查，但是改为 128 应该是个较普遍的值。

set backlog to 128

---

skynet-src/socket_epoll.h
skynet-src/socket_kqueue.h
skynet-src/socket_poll.h
skynet-src/socket_server.c

在macosx上面socket断开连接，调用read接口有概率会返回`RST`错误。根据kqueue手册 [kqueue event](https://www.freebsd.org/cgi/man.cgi?kqueue)
```
If the read direction of the socket has shutdown,
then the filter also sets EV_EOF in flags,	and
returns the socket	error (if any) in fflags.  It
is possible for EOF to be returned	(indicating
the connection is gone) while there is still data
pending in the socket buffer.
```
当socket关闭时，kqueue会写`EOF`flag，所以需要对kqueue的event 添加`EOF`flag，从而关闭关闭socket.
参考实例： [kqueue tutorial](https://wiki.netbsd.org/tutorials/kqueue_tutorial/)
PS: 此问题只会在kqueue上面才会出现， epoll并不会有问题。

fix kqueue eof event

---

service/clusteragent.lua

当有1个以上的co进入queryname,后面的协程有可能在未返回的co之前执行（第一个已经返回），导致cluster消息乱序

queryname并发导致消息乱序

---

test/testhttp.lua

**recall dns.server()**
_false	./lualib/skynet/dns.lua:340: assertion failed!_

dns reInit bug

---

skynet-src/skynet_daemon.c

目前使用r+打开，如果旧的pid比新的pid长，会导致有残留的数字在pid文件中。

修改pid打开方式为w+

---

Makefile
examples/simpleweb.lua
lualib-src/ltls.c
lualib/http/httpc.lua
lualib/http/tlshelper.lua
test/testhttp.lua

通过openssl的bios模块，用原生的socket添加了https client和server功能。
client：
使用方法为原来`httpc.get`接口中的`host`参数添加protocol的支持。 例如：之前是`httpc.get("baidu.com")` 默认为http, 改为`httpc.get("https://baidu.com")` 即为`https`请求。兼容原来的缺省protocol为`http`.
server:
调用`tlshelper.lua`中的`newctx()`创建一个唯一的`SSL_CTX`，调用`set_cert`设置好`certfile`和`private key`.生成对应的`initfunc`, `readfunc`, `writefunc`, 进行操作处理客户端的请求。具体详情查看下`simpleweb.lua`.

add https client and server support by bios

---

lualib-src/ltls.c

使用`httpc.post("https://baidu.com", "/", {})`, `form`参数为空表，会导致 https://github.com/cloudwu/skynet/blob/7746193b5fc4ff855ea7b2b11cc05cf9356563ba/lualib/http/httpc.lua#L29 写入的`content`为空串，从而导致`ltls.c`中`_ltls_context_write`函数通过bio读取到的加密数据长度`all_read`为0，抛出`./lualib/http/httpc.lua:181: ./lualib/http/tlshelper.lua:72: bio_read error when _ltls_context_write`异常。 现改为返回空串，取消异常。

fix post with https

---

3rd/lua/lstring.c
lualib/http/internal.lua

调整了判断 http header的判断长度时机，对于请求的数据比较大的情况(`readbytes`返回包含了正常的header和body)，由于优先判断了`LIMIT`导致正常请求也被判断为攻击，抛出`[socket error]`; 所以调整了判断`LIMIT`的顺序。

fix check header limit

---

lualib/skynet/cluster.lua

类似#870
这样的修改有个额外的问题，send有可能抛出异常（之前的send不会）

bugfix:cluster初始化节点的时候有可能导致消息乱序

---

lualib/skynet/cluster.lua

Revert "bugfix:cluster初始化节点的时候有可能导致消息乱序"

---

lualib/skynet/debug.lua
service/launcher.lua

since lua 5.3, collectgarbage count did not return bytes:
The call collectgarbage("count") now returns only one result. (You can compute that second result from the fractional part of the first result.)
from https://www.lua.org/manual/5.2/manual.html#6.1:
"count": returns the total memory in use by Lua in Kbytes. The value has a fractional part, so that it multiplied by 1024 gives the exact number of bytes in use by Lua (except for overflows).

collectgarbage count change to lua 5.3

---

Makefile

1. Starting from jemalloc 5.0, valgrind integration has been removed. see [link](https://github.com/jemalloc/jemalloc/issues/369
)
2. Build jemalloc with --enable-prof has minimal overhead. see [link](https://github.com/jemalloc/jemalloc/issues/1496)

build jemalloc with --enable-prof

---

skynet-src/malloc_hook.c

在macosx上面开启 `NOUSE_JEMALLOC`进行编译后运行会报错:
```
lua loader error : error loading module 'skynet.core' from file './luaclib/skynet.so':
dlopen(./luaclib/skynet.so, 6): Symbol not found: _mallctl_cmd
Referenced from: ./luaclib/skynet.so
Expected in: flat namespace
in ./luaclib/skynet.so
stack traceback:
[C]: in ?
[C]: in function 'require'
./lualib/skynet.lua:2: in main chunk
[C]: in function 'require'
./service/bootstrap.lua:1: in local 'main'
./lualib/loader.lua:48: in main chunk
```

fix use NOUSE_JEMALLOC

---

skynet-src/socket_kqueue.h

我这边打印了下， 确实会有可能`EV_EOF`和`EVFILT_READ`同时出现。测试用例很简单，就是用skynet中的`simpleweb.lua`作为简单的web服务，放在一台linux服务器上面。 之后再本地macosx上面用testhttp.lua`发起请求，很大概率会出现。
问题是，我记得早期是因为有了`EVFILT_READ`事件之后，如果当时还有`EV_EOF`flags的话调用`read`接口这个会拿到`RST`错误的。当时查了文档是说要优先判断`EV_EOF`。所以就加了优先判断`EV_EOF`。难道是新版本的macosx把这个问题当成bug给修复了？ Orz
我这边测试是没问题的， @keventan 你可以测试下，这个改法比较简单。;D

#1014 fix kequeue eof when read

---

lualib-src/lua-sharetable.c
lualib/skynet/sharetable.lua

对`sharetable`模块加了`update`接口，用来做热更新。 使用示例如下：
~~~.lua
-- 在一个service中执行更新新的table
sharetable.loadfile("res", new_resource) 
-- 在需要更新的service中执行
sharetable.update("res")
~~~
`update`的实现是将新的`sharetable`和老的`sharetable`做对比， 生成一个`replace_map`，之后遍历整个vm进行替换所有的需要替换的`table`对象。

add sharetable update

---

lualib-src/ltls.c

add SSL_CTX_new error string

---

service/clusterd.lua

在 kubernetes 集群中 socket 连接长期没有通信会被 IPVS 断开，断开时间是900s，远短于内核 Keep Alive 时间 2小时。该链接断开后，只有在下一次 write 时才会发现 Connection reset by peer，导致 Call failed。所以添加了一个接口，希望可以获取到节点内当前发生过通信的所有节点信息，以便进行健康监测。

add senders command in clusterd service

---

lualib/skynet.lua

dispatch 调用 ignoreret 以后，发生错误抛出异常，会因为 session_coroutine_address 持有协程引用导致协程无法回收，从而发生内存泄漏。

fix: coroutine leak when dispatch failed

---

lualib-src/lua-sharetable.c
lualib/skynet/sharetable.lua

暂时解决了issue #1096  的问题。 之所以更新不了是因为当通过`coroutine.create(func)`创建出一个co时，同时未执行resume时，是处于suspended状态。此时通过`debug.getinfo`是无法取到`func`的。因为当前co还未被resume过，调用栈是为空。 从而导致func是没法通过lua函数`getinfo`被遍历到，无法做到更新替换。
在lua-sharetable.c代码中实现了`lco_stackvalues`函数来获取创建时的func。
~~~.c
static int
lco_stackvalues(lua_State* L) {
lua_State *cL = lua_tothread(L, 1);
luaL_argcheck(L, cL, 1, "thread expected");
int n = lua_gettop(cL);
if(n > 0) {
int i=0;
lua_checkstack(L, n);
for(i=0; i<n; i++) {
setobj2s(L, L->top, cL->top - n + i);
api_incr_top(L);
}
return n;
}
return 0;
}
~~~

match origin fucntion of thread

---

examples/simplewebsocket.lua
lualib/http/websocket.lua

取消了 `websocket.accept` 主动`error`，改成与`httpd.read_request`一致，返回是否正常退出，以及错误信息。

add result of accept

---

skynet-src/socket_kqueue.h

修复问题 #1122 。 之前之所以加上对eof的优先判断，在#858 这个PR中有说明。现在我在我macosx上面测试 `EVFILT_READ` 和`EV_EOF`同时出现时调用`read`系统函数并不会出现`RST`错误了。现在怀疑是macosx新版本把这个行为做了修改。 所以，暂时对read时去掉了对eof的优先判断。

fix kqueue read with eof

---

lualib/skynet/sharetable.lua

fix #1124 issue.  当调用`match_thread`的是当前co，会跳过从`sharetable.update`函数开始之后的函数调用，但在替换函数内部upvalue和local变量时，因为调用了`match_funcinfo`函数，所以要对level+1.

fix sharetable update when match self coroutine

---

lualib-src/lua-sharedata.c

fix sharedata emptyslot

---

lualib/skynet/db/mongo.lua
lualib/skynet/socketchannel.lua

See issue #1145
改进 socket channel, 在 auth 失败后，会尝试连接 backup 列表（若提供）中下一个 host 。
之前的实现 socket channel 仅当连接主 host 失败后才尝试连接 backup 。
由于 socket channel 实现了这个特性， mongodb driver 就不必额外实现 pickserver 功能。在找不到主节点时，直接抛出 error 即可。
这个 patch 的主要改变是将原来的 `connect_once` 函数包装了一层，原来逻辑放在内部函数 `_connect_once` 中，包装层会复制一份 backup 列表，在 `_connect_once` 建立连接失败（包括 socket 建立失败，及 auth 过程发生 error ）后，尝试列表中没有试过的 host 。
注: 如果 auth 过程主动调用 changehost ，而非抛出 error ，则会重试整个 `connect_once` 过程。
btw，这个 patch 改动并不太大。之所以 diff 看起来很复杂，是因为 `_connect_once` 相对 `connect_once` 改动了缩进层次。

Improve socketchannel

---

lualib/http/websocket.lua

issue #1152  握手失败时应当触发`close`消息和关闭socket。

fix handshake error

---

lualib/http/websocket.lua

A Pong frame sent in response to a Ping frame must have identical
"Application data" as found in the message body of the Ping frame
being replied to.
https://tools.ietf.org/html/rfc6455#section-5.5.3

websocket的pong应该返回ping夹带的数据

---

lualib/skynet/db/mysql.lua
test/testmysql.lua

客户端其实是没法直接通过数据类型判断服务器发来的数据是否有无符号的.需要通过列定义包中的标志位来判断.
[https://mariadb.com/kb/en/resultset](https://mariadb.com/kb/en/resultset)
整型数据也不能统一按符号型(I\<n\>)处理,不然会导致错误.比如服务器存储了一个unsigned tinyint,其值为0xFF,都按照有符号整型处理,客户端是取不到255(<I1)这个值的,只能取到-1(<i1).

mysql : 修复读写负数导致溢出处错误 (#1182)

---

lualib-src/sproto/sproto.c

buffer overflow occurs when packing a string with length = 2046 or 2047

fix sproto write_ff buffer overflow

---

lualib/skynet/sharetable.lua

修改了sharetable 的update遍历当前coroutine的行为。改为match前先遍历，同时添加了record_map记录。

优化sharetable更新

---

lualib-src/lua-memory.c
service/debug_console.lua
skynet-src/malloc_hook.c
skynet-src/malloc_hook.h

- 1, add opts arg for mallctl,dumpinfo
- 2, collect jemalloc.mem info
- 3, add debug_console cmd: jmem
```
jmem
stats.active       14888960     14.20 Mb
stats.allocated    14265888     13.61 Mb
stats.mapped       42164224     40.21 Mb
stats.resident     18509824     17.65 Mb
stats.retained     16556032     15.79 Mb
<CMD OK>
```

Add jemalloc mem stat

---

3rd/lua/lapi.c

`struct TString` 结构改了
```c
/*
** Get the actual string (array of bytes) from a 'TString'.
*/
#define getstr(ts)  ((ts)->contents)
```

fix lua_sharestring

---

lualib/skynet/sharetable.lua

`sharetable.update` 时，进行`match_thread` 对`stack_values_tmp` 变量会重入。导致`match_value` 一个nil值。

#1229 fix sharetable update

---

lualib-src/lua-bson.c

在使用mongodb时，有时候数据没有超过32位，但是需要指定数据类型为int64

增加一个指定数据类型为int64的方法

---

lualib/skynet/sharetable.lua

1. 将`match`尽可能的改成了tail call；减少出现`stack overflow`错误的概率。(lua5.4.2改为了stackless调用，问题不那么严重)
2. 修复了在调用`sharetable.update`的coroutine中，调用栈替换错误导致`replace_map`被替换的bug。

fix sharetable update and tail call

---

service/launcher.lua

```
launcher.lua:35: attempt to index a boolean value (local 'resp')
```

Fix typo: Causes an error when `resp` is false

---

lualib/skynet.lua
test/testtobeclosed.lua

skynet协程中的`to-be-closed`的值在非正常情况下(`raise error`, ```skynet.exit()```)没有被正确释放
bty:
`session_id_coroutine`表中有BREAK的值, 有些接口需不需要加上一些判断(判断类型是thread)

to-be-closed

---

skynet-src/socket_server.c

当收到客户端`shutdown SHUT_WT`时会判断当前`wbuffer`中是否还有数据， 如果是有数据将会进入`SOCKET_TYPE_HALFCLOSE`状态，等待发送完全之后再`close socket`.
https://github.com/cloudwu/skynet/issues/50 此issue可以解决。

fix socket half close

---

lualib/skynet/db/mongo.lua

使用 Mongodb 4.4.1 版本时发现错误消息的字段为 `r.errmsg`

fixed mongodb werror return errmsg

---

lualib-src/ltls.c
service/bootstrap.lua

1. 添加了`ltls.init.c`接口用来做`ltls`的初始化。
2. 初始化接口在`bootstrap`中由创建的`ltls_holder`服务来进行调用，保证整个skynet进程生命周期中so只会load一次。
3. 目前是导出了`constructor`和`destructor`两个接口，`destructor`接口暂时没做调用。
4. 开启https功能现在多了一个参数，需要在`config`启动文件里面加上`enablessl = true`。

 bugfix ltls init #1314

---

lualib/skynet/socket.lua
lualib/skynet/socketchannel.lua
skynet-src/socket_server.c
skynet-src/socket_server.h

讨论见 #1358 
如果建立一个连接但长期不使用，目前比较难检测到对端关闭连接。因为只有使用 socket.read 或 socket.block 才能根据返回值知道对端关闭事件。而 socket.read 和 socket.block 不能同时使用，这给 socketchannel 模块监测对端关闭事件造成了困难。
所以增加了 socket.onclose(fd, cb_func) 注册回调函数。
利用这个回调函数，在 socketchannel 的 by_order 模式中，检测 socket close 事件。注： by_session 模式独立线程一直在读 socket ，所以不需要。
一旦 onclose callback 被调用，通过判断 `self.__wait_response` 可以知道 channel 正在等待下一个请求（通道闲置）。此时，再次核对当前的 self.__sock 时候还是注册时的对象（socket channel 因为重连，会更换 self.__sock）；确认后主动 close fd 。
另外，在 `dispatch_by_order` 线程函数中，`pop_response` 之后，`get_response` 之前，都应该检查内部连接是否关闭（`self.__sock` 在关闭后为 false)。避免把 false 当作 sock 对象传给回应处理函数。
这一系列处理可以避免 : sockchannel 的对端主动关闭连接，而我方迟迟不处理关闭事件，而让连接不能完全关闭。

socket.onclose()

---

skynet-src/skynet_start.c

在使用gate.so作为boostrap启动的时候，发现boostrap只会读到一个参数传给service_gate, 导致gata服务不能正常启动。
eg: bootstrap: "gate arg1 arg2 arg3".
现在将arg1到字符串结尾到放进args里，而不是仅仅取得arg1.

Fix boostrap only support 1 param.

---

lualib-src/ltls.c

修改了下 通过SSL_get_error 获取到错误以后，清理错误

1.修复前一个ssl错误没清，导致后面的正常ssl调用操作 获取到这个错误

---

lualib/skynet/require.lua

在 skynet.init 过程中如果 require 了当前模块，目前会一直挂起。因为 skynet.init 认为也是模块加载的一部分，所以这里对这类逻辑 assert 掉，效果同模块级别互相 require 最终也会报错类似。
麻烦云风看看！

when skynet.init require the loading module caused circular dependency

---

lualib-src/lua-seri.c

fix lua-seri rb_read

---

service/sharedatad.lua

value字段引用了原来的lua数据表，导致多占用了一定内存

sharedata 去掉多余的value字段

---

3rd/lua/lauxlib.c

在使用 `codecache` 并且后台启动的情况下，`loadfile(nil)` 会触发 `save_proto(NULL, proto)`，此时出错后会直接 `panic`。
处理 `filename` 为 `NULL` 的情况，不做 `cache` 的处理。

panic while reading from stdin

---

lualib/skynet/sharetable.lua
test/testsharetable.lua

支持批量获取配置指针。
测试效果如下:
```
[root@f3e91cf322aa skynet]# ./skynet examples/config
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000004] connect from 127.0.0.1:34610 4
[:01000006] LAUNCH harbor 1 16777221
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua testsharetable
[:0100000a] LAUNCH snlua service_provider
[:0100000b] LAUNCH snlua service_cell sharetable
y	table: 0x7f9156646280
hello world	true
x	1
1	1
2	2
3	3
test_two	1	2
test_two	message	hello …
```

feat: add sharetable queryall

---

lualib/skynet/sharetable.lua
test/testsharetable.lua

建议接受可空参数 返回所有
_Originally posted by @sniper00 in https://github.com/cloudwu/skynet/issues/1536#issuecomment-1040309038_
测试效果如下：
~~~
[root@f3e91cf322aa skynet]# ./skynet examples/config
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000004] connect from 127.0.0.1:34632 4
[:01000006] LAUNCH harbor 1 16777221
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua testsharetable
[:0100000a] LAUNCH snlua service_provider
[:0100000b] LAUNCH snlua …

perf: add sharetable queryall default behavior(all share data)

---

lualib-src/lua-crypt.c

提高base64的兼容性，在密文没有提供=号结束符号时也能正确解码，行为与PHP里的base64decode 一致

提高base64算法的兼容性

---

examples/cluster1.lua
lualib/skynet/cluster.lua
service/clusterd.lua

当前我们一些服务需要关闭然后重启，当前命名主要采用的是**服务名称_服id_模块id**，所以需要解决cluster.register注册冲突问题。
之前一些服务使用的方案是拼一个递增的序列，然后使用方调用一次接口获取一下服务名称也可避免这个问题。
不是那么方便所以想支持直接取消注册然后重新注册。

feat: add cluster.unregister

---

examples/config.handle
skynet-src/skynet_handle.c
test/testhandle.lua

使用旧代码可以重现： `./skynet examples/config.handle`
原因是当 s->slot[0] 为 NULL 时，即 context 为 NULL，对 NULL 取 handle 值会崩溃。需要构造出 slot[0] 为空，其他值都不空，且 handle_index 处于 (HANDLE_MASK - slot_size, HANDLE_MASK] 范围内时注册新服务。
这个 bug 是一位群友发现的，我只是写了个找到不修改 HANDLE_MASK 值来重现的测试用例，附件是群友的分析。
[handle的分析.md](https://github.com/cloudwu/skynet/files/8481336/handle.md)

Fix handle register when slot[0] is null will segmentation fault

---

lualib-src/lua-socket.c
lualib/skynet/cluster.lua
lualib/snax/gateserver.lua
service-src/service_gate.c
service/clusterd.lua
service/gate.lua
skynet-src/skynet_socket.c
skynet-src/skynet_socket.h
skynet-src/socket_server.c
skynet-src/socket_server.h

为了简化配置服务使用的端口，采用了系统随机端口。于是修改了socket.listen函数的返回值
``` lua
local id, port = socket.listen('0.0.0.0', 0)
skynet.error(port)
```

 更新socket.listen函数，返回id与port。当传入的port为0时，会返回绑定的随机端口

---

lualib-src/lua-socket.c
skynet-src/skynet_socket.c
skynet-src/skynet_socket.h
skynet-src/socket_server.c
skynet-src/socket_server.h

socket_server.c中do_bind的port参数类型改为了指针，导致调用socketdriver.udp后coredump

udp socket bugfix

---

lualib-src/lua-mongo.c
lualib/skynet/db/mongo.lua
test/testmongodb.lua

1. 统一使用 OP_MSG 作为双向通信协议，删除其他 OP_CODE，不再支持 3.6 以前的 mongodb。
2. 仅实现了 payload_type 0，payload_type 1 用于实现 batch insert，目前没有用到。

mongodb 交互协议调整为 OP_MSG

---

3rd/lua/makefile
Makefile

This reverts commit dfc706615e585713ecf9384f7a3cb71ed72dca6b.
mac m1 环境下编译 lua 报错，默认 clang 版本是13，先回退 lua makefile。
不过社区有说修复了这个问题，应该是要升级 clang 才行。
https://reviews.llvm.org/D119788
https://discourse.llvm.org/t/why-does-march-native-not-work-on-apple-m1/2733
env：
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```shell
gcc -Wall -O2  -Wfatal-errors -Wextra -Wshadow -Wsign-compare -Wundef -Wwrite-strings -Wredundant-decls -Wdisabled-optimization -Wdouble-promotion -Wmissing-declarations  -Wdeclaration-after-statement -Wmissing-prototypes -Wnested-externs -Wstrict-prototypes -Wc++-compat -Wold-style-definition  -Wlogical-op -Wno-aggressive-loop-optimizations  -std=c99 -DLUA_USE_LINUX …
```

Revert lua makefile of "update lua"

---

lualib/http/websocket.lua

增加 websocket.real_ip 方法，获取nginx透传的真实客户端ip地址。

read 'x-real-ip' header from nginx in websocket lib.

---

lualib/skynet/db/mongo.lua

getMore命令的可选字段batchSize的值必须是正整数，语义是每次批量返回文档数量。
cursor.limit方法的参数范围是 -2^31到 2^31，语义是返回的最大总文档数量。
两者不应该混用。

bugfix: mongo getMore command field batchSize cannot replace with limit

---

lualib/snax/gateserver.lua

在`MSG.open`中，当`client_number >= maxclient`时，连接被关闭后触发`MSG.close`，导致`client_number`没有`+1`的情况下被`-1`

修复client_number计数错误

---

lualib/skynet/cluster.lua
service/clusterd.lua

`cluster`启动的`gate`没有传入`maxclient`参数，导致默认连接数限制在`1024`。

 为cluster.open添加maxclient参数

---

lualib-src/lua-skynet.c

~~~.lua
local function test_crash_service()
local c = require "skynet.core"
print("test_crash_service start..")
c.callback(function () end)
c.callback(function () end)
print("test_crash_service finished")
collectgarbage "collect"
end
local Service = require "skynet.service"
Service.new("test_crash_service", test_crash_service)
~~~
被执行后将会出现`segmentation fault`，导致crash。
因为调用`lcallback` 时会创建新的`coroutine` ，来处理后续的回调函数。但如果该函数是在被`_cb` 中触发的话，会导致当前正在被使用的`cb_ctx` 失去被`callback_context` key持有的引用。此时如果再触发gc行为，将会导致当前正在被执行的`coroutine` 和 `cb_ctx` 被回收掉，从而导致crash。
对`struct callback_context` 结构添加`bool calling` 字段，表示当前`_cb` 正在被执行中，在调用`lcallback`时 会判断`calling`, 如果该`cb_ctx`正在被调用执行， 将会被`last_callback_context` 所持有，从而避免被gc回收。

修复设置 callback导致的crash问题

---

lualib/http/websocket.lua

调用`websocket.write`会因为`ws_pool`已经没有而断言，想用`is_close`做`write`的前置判断，`socket.invalid` 和 `socket.disconnected` 并不能做到。

websocket添加is_close方法

---

lualib-src/ltls.c

参考文档：https://www.openssl.org/docs/manmaster/man7/migration_guide.html
ERR_load_*(), ERR_func_error_string(), ERR_get_error_line(), ERR_get_error_line_data(), ERR_get_state()
OpenSSL now loads error strings automatically so these functions are not needed.
```
cc -g -O2 -Wall -I3rd/lua  -fPIC --shared -Iskynet-src -L -I lualib-src/ltls.c -o luaclib/ltls.so -lssl
lualib-src/ltls.c: In function ‘ltls_init_constructor’:
lualib-src/ltls.c:414:9: warning: ‘ERR_load_BIO_strings’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
414 |         ERR_load_BIO_strings();
|         ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/cryptoerr.h:17,
from /usr/include/openssl/crypto.h:38,
from /usr/include/openssl/bio.h:30,
from /usr/include/openssl/err.h:29,
from …
```

修复 openssl3 deprecated warning ERR_load_BIO_strings

---

lualib-src/lua-sharedata.c

```
local skynet = require "skynet"
require "skynet.manager"
local sharedata = require 'skynet.sharedata'
skynet.init(function()
local int32 = 123
local int64 = (1 << 32) + 123
local data = {
[int32] = 1,
[int64] = 2,
-- test = 3,
}
sharedata.new("test", data)
end)
skynet.start(function()
local data = sharedata.query("test")
print(data[2])
skynet.abort()
end)
```
误用大于32位的数字做 key, 有极少概率导致严重问题。
如上这段代码可以导致进程死循环或者崩溃

避免 sharedata 误用大于32位数字做 key 时,可能导致程序崩溃

---

lualib/skynet/db/mysql.lua

修复mysql.execute的变长参数最后一个为nil时的NULL位图错误

---

lualib/http/websocket.lua

bugfix #1837   解决在handshake阶段读取header时，错误的丢掉了header payload。

fix read_handshake

---

lualib/http/httpc.lua

在进行https握手时，会有小概率在进行密钥协商前，tcp流卡住，导至不能有效timeout行为

在进行https握手时，会有小概率在进行密钥协商前，tcp流卡住，导至不能有效timeout行为

---

lualib/skynet.lua
skynet-src/skynet_server.c

消息堆积时，A服务send消息到B服务让其skynet.exit()，在此之后且skynet.exit还没执行，有C服务call B服务，则会出现C服务一直挂起的情况。
复现用例，需将消息权重调大才能必现
--------------dummy------------------
``` lua
local skynet = require "skynet"
local CMD = {}
local function calltest()
local handle = skynet.uniqueservice("calltest")
local ok = skynet.call(handle, "lua", "test1")
for i = 1, 10000000 do
skynet.send(handle, "lua", "test1")
end
skynet.send(handle, "lua", "EXIT")
print("in???????????????????????????????????")
ok = skynet.call(handle, "lua", "test1")
end
skynet.start(function()
skynet.dispatch("lua", function(_, _, cmd, ...)
local f = assert(CMD[cmd], cmd)
skynet.retpack(f(...))
end)
calltest()
end)
```
------------calltest-----------------
``` lua
local skynet = require "skynet"
local CMD = {}
function CMD.test1()
return "xxx"
end
function …
```

修复执行skynet.exit后别的服务call有概率卡死

---

lualib/skynet.lua

当处理同时多条消息时，假如第一条是skynet.exit，后面有timeout的消息(source = 0)，就会导致报错 Invalid service address 0
skynet.exit 会替换 callback函数，source = 0时使用c.send发送消息报错

session或者source为0时不回消息

---

lualib/skynet.lua

我们项目中定制了error，但是不希望skynet error使用我们定制的error。 看到assert有提前记下来，就想补个error的

skynet使用原生error，防止给替换

---

lualib/skynet/socketchannel.lua

在`auth`认证失败时，会主动调用`close_channel_socket`,但是`pop_response`的携程并没有唤醒退出，导致内存泄漏。
修复前:
调试打印没有到`over`,也就是`dispatch_by_order`函数结束的地方。
弱引用表关联的channel对象会一直涨，说明没有释放(主动调用gc也不行)。
修复后:
`dispatch_by_order`函数执行完了。
调用gc后，弱引用表对象减少了，说明释放了。

fix socketchannel mem leakage

---

service-src/service_snlua.c

修复打开DEBUG_LOG时，编译错误

---

lualib/skynet.lua

skynet.wait中使用的session增加回绕判断

---

lualib-src/ltls.c
lualib/http/httpc.lua
lualib/http/tlshelper.lua

有些https服务器会检查握手时server_name，一般https客户端都会主动设置

https set extension:server_name

---

examples/client.lua

原 recv_package 最后一行是调用 unpack_package, 如果 unpack_package 时，还是没收完一个包的话，会返回 nil, 导致误以为连接断开。
ps: 我是在 server - server 之间 使用 skynet.socket api , 复用这段代码出现的问题. client.socket 可能复现不了。

fix client recv_package

---

lualib-src/lua-cluster.c

调用`cluster.send(node, address, ...)`
当`address`是**空字符串**时，错误描述不准确："name is too long"
改成："name length is invalid, must be between 1 and 255 characters"

fix: 调整一个错误描述

---

lualib/http/websocket.lua

```txt
[:0000002e][20241206 15:22:36 74]lua call [0 to :2e : 0 msgsz = 38] error : [31m../../skynet_fly/skynet/lualib/skynet.lua:1031: ../../skynet_fly/skynet/lualib/skynet.lua:459: ../../skynet_fly/skynet/lualib/skynet\socket.lua:493: assertion failed!
stack traceback:
[C]: in function 'assert'
../../skynet_fly/skynet/lualib/skynet\socket.lua:493: in function 'skynet.socket.warning'
../../skynet_fly/skynet/lualib/http\websocket.lua:438: in function 'http.websocket.accept'
../../skynet_fly/service/ws_slave.lua:122: in local 'f'
../../skynet_fly/lualib/skynet-fly\utils\skynet_util.lua:65: in upvalue 'f'
../../skynet_fly/skynet/lualib/skynet.lua:409: in function <../../skynet_fly/skynet/lualib/skynet.lua:381>
stack traceback:
[C]: in function 'assert' …
```

fix websocket accept mem leakage

---

service/datacenterd.lua

datacenterd query接口查询时,当db为nil时,终止递归

datacenterd query接口查询时,当db为nil时,终止递归

---

skynet-src/skynet_server.c

* 测试过程中发现有个服务的message数量显示是负数[-214011719]，判断超int了

fix message数量过多导致int溢出

---

lualib/skynet/socketchannel.lua

##`dispatch_by_session` 修复后测试结果
```txt
[:0000000f][20241230 17:30:10 01]connect from 127.0.0.1:60548
[:0000000f][20241230 17:30:10 01]recv: session = 1 data = hello world 1
[:0000000f][20241230 17:30:10 02]recv: session = 2 data = hello world 2
[:0000000f][20241230 17:30:10 03]recv: session = 3 data = hello world 3
[:0000000f][20241230 17:30:10 04]recv: session = 4 data = hello world 4
[:0000000f][20241230 17:30:10 05]recv: session = 5 data = hello world 5
[:0000000f][20241230 17:30:10 06]recv: session = 6 data = hello world 6
[:0000000f][20241230 17:30:10 07]recv: session = 7 data = hello world 7
[:0000000f][20241230 17:30:10 08]recv: session = 8 data = hello world 8
[:0000000f][20241230 17:30:10 09]recv: session = 9 data = hello world 9
[:0000000f][20241230 17:30:10 10]recv: session = …
```

fix socketchannel closed thread not wakeup

---

lualib/skynet/db/mysql.lua

#2034 
修复了通过如下方法解析date类型数据的问题
```lua
-- day在MySQL中是date类型
local sql = "select day from tab where day = ? "
local stmt_sql = db:prepare(sql)
local res = db:execute(stmt_sql, "2020-01-01")
```

* 增加mysql使用execute方法解析date格式数据

---

lualib-src/lua-sharedata.c

resolves #2036 
允許對 sharedata 返回的 table 做讀取 `t[nil]`
會返回 `nil` 而不是報錯
詳細討論見該 issue

allow `t[nil] => nil` in table returned by sharedata

---

service-src/service_gate.c

当前端主动关闭socket时，应用层无法正确的 kick fd  `int id = hashid_remove(&g->hash, message->id);`  产生 CLOSE-WAIT

fixed: service_gate_c  half close

---

service-src/service_snlua.c

这个地方注释有点问题，应该是在检查 start time 是否为 nil

fix comment: check start time
