skynet-src/skynet_main.c

error report fix

---

lualib/http/httpc.lua

使用httpc.post，由于没有在默认的header里面设置host调用request时会有问题。

fix: httpc.post

---

lualib/http/httpc.lua

fix: httpc.get

---

service/console.lua

输入：
svc  -> 用snlua启动svc服务
snax svc -> 用snax启动svc服务

console服务增加启动snax服务功能

---

Makefile
service-src/service_gate.c

modify Makefile and add lua clean
modify service-src/service_gate.c space to tab

修改Makefile，添加lua的清理

---

examples/share.lua
lualib-src/lua-seri.c

lua 协议支持 sharedata 的序列化
服务间通信构造一些使用到 sharedata 的临时参数时不用进行额外的处理

support sharedata serialization

---

examples/login/client.lua

fix invalid fd after reconnected, used in unpack_f

Pr-fix-login-client

---

lualib-src/sproto/lsproto.c

lunpack optimize, do not unpack twice if r <= osz

Pr-optimize-sproto-unpack

---

examples/share.lua
lualib-src/lua-seri.c

clean lua stack when wb_table_metapairs returns

sharedata serialization bugfix

---

service/debug_console.lua

telnet 的输入以 \r\n 结尾，所以输入 cont 永远不会退出

not work with telnet due to \r\n

---

3rd/lua/lua.c

add missing luaS_exitshr call

---

lualib/snax/gateserver.lua

gateserver close 

---

skynet-src/socket_server.c

clear_closed_event是针对 https://github.com/cloudwu/skynet/issues/109 而加上的

delete two clear_closed_event call

---

service-src/service_gate.c

bugfix: remove Wformat warning

---

lualib/md5.lua

add hmac_md5

---

lualib-src/lua-sharedata.c

delete this line and I can compile skynet  normally

 repeated “struct table" of line 19

---

lualib/skynet/debug.lua
lualib/skynet/remotedebug.lua
lualib/snax/hotfix.lua

修复调试模块调试结束后定时器没有取消的问题

---

lualib/mysql.lua

A query may execute multi sql statements.If an error occurs for any sql, the result should return the error info.

error deal for query containing multi statement

---

lualib/socket.lua

delete unused local variable table "udp_socket"

delete unused local variable

---

lualib/skynet/coroutine.lua

skynet.coroutine

---

3rd/lua/ldebug.c
3rd/lua/ldo.c
3rd/lua/lparser.c
3rd/lua/lundump.c
3rd/lua/lvm.c

bugfix, error when use lua apicheck

---

lualib/sharedata.lua
lualib/skynet.lua
service/sharedatad.lua

skynet.pcall support vararg; sharedata loader can use custom args

---

lualib/skynet/debug.lua
service/debug_console.lua

add vararg for INFO debug console command

---

lualib-src/lua-bson.c

lua_bson的encode方法增加对有自定义__pairs的table的支持

---

lualib/mongo.lua

the output of  command "ismaster"  doesn't contain "primary" field when connect to a replica sets in some MongoDB services (e.g. 阿里云).

auto determine primary host

---

lualib-src/lua-socket.c

The size of first chunk ([2]) is 16 struct buffer_node, and the second
size is 32 ...

fix comment for lpushbuffer

---

lualib/skynet.lua

skynet.lua raw_dispatch_message

---

lualib/skynet/coroutine.lua

nice error log in skynet coroutine

---

lualib/skynet/datasheet/builder.lua

datasheet在monitor接口里面产生的reponse在release接口里面没有释放

skynet.response() leak

---

README.md

I've changed the "Only in Chinese now" to "currently only available in Chinese" in README.md.

Rearranged sentence to be reader friendly.

---

lualib/skynet/debug.lua
lualib/skynet/inject.lua
service/debug_console.lua

debug console inject cmd support args

---

test/testmongodb.lua

mongo driver 改了接口返回值，修改下相关的测试用例

fix mongodb testcase

---

Makefile

fix tls make

---

lualib-src/lua-memory.c
service/debug_console.lua
skynet-src/malloc_hook.c
skynet-src/malloc_hook.h

Provide a way to do  memory profiling dynamically from debug_console.

Add jemalloc heap profilling in debug console

---

lualib-src/ltls.c

`SSL_read`缓存中可读的长度尽管超过`sizeof(outbuff)` 4096的长度，但是返回的`read`是有可能会小于4096。根据文档 https://www.openssl.org/docs/man1.0.2/man3/SSL_read.html 
改为通过判断`SSL_ERROR_WANT_READ`和`SSL_ERROR_WANT_WRITE`来识别是否`SSL_read`读完。

#1016 bugfix SSL_read and SSL_do_handshake

---

lualib-src/ltls.c

添加了`SSL_read`和`SSL_write`返回0的校验。

fix SSL_read and SSL_write return 0

---

lualib-src/ltls.c

`BIO_read`和`BIO_write`也加了返回值为0的判断。 同时将`_bio_read`改为了根据`BIO_ctrl_pending`的返回值来判断是否继续读。

fix BIO_read and BIO_write return 0

---

3rd/lua/lstring.c

有概率出现total为0但是garbage不为0的情况

---

3rd/lua/lstring.c

collectref的时候减少nuse

---

3rd/lua/lua.h
3rd/lua/lualib.h
3rd/lua/lvm.c

lua_checksig LUA_CACHELIB

---

examples/simplewebsocket.lua
lualib/http/websocket.lua

添加了获取`websocket_id`的`addr`信息的接口:`websocket.addrinfo(ws_id)`. 对于回调接口`handshake` 添加了`url`参数。

add websocket address and url param

---

lualib/skynet.lua
lualib/skynet/debug.lua
service/debug_console.lua

获取挂起协程的时候合并同类项，返回总数，避免大量输出刷屏，也方便定位问题

uniqtask for gm

---

3rd/lua/ltable.c

rawset目前可以修改sharetable的数据!
这个修改会涉及到的接口
```
lua_rawset
lua_rawsetp
lcode.c 中的addk
luaX_newstring
luaH_resize
luaH_newkey
```

luaH_set check shared table

---

lualib-src/lua-socket.c
service-src/service_harbor.c
skynet-src/skynet_socket.c
skynet-src/skynet_socket.h
skynet-src/socket_buffer.h
skynet-src/socket_server.c
skynet-src/socket_server.h

Add some new APIs, `skynet_socket_sendbuffer` , `skynet_socket_sendbuffer_lowpriority` , and `skynet_socket_udp_sendbuffer` for removing memcpy where sending lua string.
See #1107

Add socket_sendbuffer

---

test/testmysql.lua

修改skynet/test/testmysql.lua，增加mysql存贮过程和blob读写示例。

增加mysql存贮过程和blob读写示例

---

test/testmysql.lua

https://github.com/cloudwu/skynet/issues/1165

修改 mysql 测试用例

---

examples/simplewebsocket.lua
lualib/http/websocket.lua

根据 #1168 的需求，在`on_message`接口处添加了`message`类型的支持。

add message type

---

lualib/skynet/db/mysql.lua
test/testmysql.lua

https://github.com/cloudwu/skynet/issues/1172

add support for charset encoding

---

lualib/skynet/db/mysql.lua

mysql : 修复读写负数导致溢出处错误

---

lualib-src/sproto/lsproto.c
lualib-src/sproto/sproto.c
lualib-src/sproto/sproto.h
lualib/sprotoparser.lua

add sproto double type

---

lualib-src/sproto/lsproto.c
lualib-src/sproto/sproto.c
lualib-src/sproto/sproto.h

update sproto double array

---

lualib-src/sproto/lsproto.c

sync sproto weak type

---

lualib/http/websocket.lua

从http请求升级到websocket

---

lualib/skynet.lua

see (https://github.com/cloudwu/skynet/pull/1323#issuecomment-759875782)

skynet.exit

---

service/debug_console.lua

skynet.debug 支持 额外 命令 在 debug_console 中 增加一个 对应 调用 自己额外命令的指令

debug_console add dbgcmd command

---

lualib/http/websocket.lua

修复延续帧 op 传递错误问题 (应当传递第一帧的 op 而非最后一帧的).
增加写数据错误时的关闭处理与 handle 触发.

fix websocket bugs

---

lualib-src/lua-socket.c

freebsd compile error

---

lualib/skynet/cluster.lua

https://github.com/cloudwu/skynet/compare/master...pigparadise:master#diff-6d46b80b0467277ded1ae8d7f33c888abbfeb4362338bfa2e56dba54e0142b2fL63
table.pack(address, ...) 这个打包的table中的子项如果是一个table，在这个初始化挂起的过程中，可能会被修改，进而会导致逻辑不符合预期。

bugfix:params changed when cluster sender is connecting

---

skynet-src/spinlock.h

improve spinlock

---

skynet-src/spinlock.h

use _mm_pause

---

lualib-src/ltls.c
lualib/http/httpc.lua
lualib/http/tlshelper.lua
lualib/http/websocket.lua

see #1459
我自己在debian 8/10 和mac上测试过，麻烦再看看

ssl request support sni(Server Name Indication)

---

lualib/http/httpc.lua
lualib/http/internal.lua
lualib/http/websocket.lua
test/testhttp.lua

See https://github.com/cloudwu/skynet/issues/1461

Request stream

---

lualib/http/httpc.lua
lualib/http/httpd.lua
lualib/http/internal.lua
lualib/http/tlshelper.lua

通过luacheck检查 ，删除未使用的变量，添加需使用的参数

modify from http folder

---

lualib-src/lsha1.c
lualib-src/lua-bson.c
lualib-src/lua-crypt.c
lualib-src/lua-mongo.c
skynet-src/atomic.h
skynet-src/spinlock.h

单独使用云大修改版lua时，兼容用cpp编译，特别是在windows下longjmp有特殊行为，和cpp交互时建议用cpp编译lua

Compat lua compile as cpp

---

service/clusterd.lua

当address被设置成false后；sender会再次命中changenode
考虑到如果到clustersender中读取closed状态的走一次msg 不如直接用cache来处理

修改clusterd node closed 后再次命中__index 会继续触发 call changenode

---

lualib/skynet/db/mongo.lua

1、增加sort_statge、skip_statge、limit_statge、count_statge替换临时table
2、改成for i = 1, 2 do self.__pipeline[len + i] = nil end清除老数据

pipline方法优化

---

lualib/skynet.lua

See #1797 
1. 设置一个危险区，当下一个 session 将落在危险区内时，开启冲突检查。
2. 在安全区内，只检查 session 是否还在安全区。
3. 首次进入危险区，记录当前所有 session 。之后的检查只在这个集合进行，因为进入危险区后产生的 session 都不会相互冲突。
4. 当发现有潜在冲突的 session 但已被排除（session 存在危险集合中，但不存在当前 session 集），可以重新计算危险区，这样可能快速切换回不检查的版本。

check conflict

---

service/bootstrap.lua

When I write "enablessl = false" in config file,  it doesn't working as expected.

check enablessl == "true"

---

lualib/http/httpc.lua

modify httpc.request

---

lualib/http/url.lua
test/testhttp.lua

类似 `http://baidu.com/get?k1=1&k2=2&k4=a%20space&k5=b%20space&k5=b%20space&k5=b%20space` 的数组参数会合并到一个 key 下。

bugfix, parsing http array form

---

lualib/skynet/db/mongo.lua

mongodb查询有时不会命中最优索引，所以支持下 hint 使用

mongo 支持 hint

---

lualib/skynet/db/mongo.lua

为了防止慢请求打爆mongodb，查询时增加 maxTimeMS 限制

mongodb 查询增加 maxTimeMS

---

lualib/skynet/db/mongo.lua

fix mongo find without limit when getMore

---

lualib/http/httpc.lua
lualib/http/httpd.lua
lualib/http/internal.lua
lualib/http/sockethelper.lua

优化http出错抛出更详细的错误信息

---

lualib/skynet.lua

task / uniqtask 处理 break / timeout_traceback 等行为不一致，统一返回逻辑。

make task/uniqtask consistent

---

lualib/http/sockethelper.lua

修复后 `connect failed host = huahua132.github.io/ port = 443 timeout = nil err = nil is_time_out = false`

fix attempt to concatenate a nil value (local timeout)

---

service/clusteragent.lua

fix_register_name

---

service/clusteragent.lua

refix register_name_mt

---

service/debug_console.lua

debug_console 增加http post，避免get url转义问题

---

service/debug_console.lua

debug_console增加getenv,setenv命令

---

lualib-src/lua-socket.c
lualib/skynet/socket.lua
skynet-src/skynet_socket.c
skynet-src/skynet_socket.h
skynet-src/socket_server.c
skynet-src/socket_server.h
test/testudp.lua

* 原来的udp接口客户端和服务端都需要先创建一个 skynet.udp socket对象. 传addr + port的时候会自动bind,当作server的udp, 不传的话,就创建一个ipv4的socket, 客户端再调用 udp_connect(addr, port) 来建立连接, 但是如果addr是ipv6的地址的话,就会报 udp socket (11) type mismatch. 的错误
* 参考 go的udp server和client的创建方法, 提供了 udp_listen和 udp_dial两个api. 通过识别 addr来自动创建 ipv4或者ipv6的socket.
* 原ipv6的用例 (会有异常)
```
local skynet = require "skynet"
local socket = require "skynet.socket"
local function server_v6()
local host
host = socket.udp(function(str, from)
print("server_v6 recv", str, socket.udp_address(from))
socket.sendto(host, from, "OK " .. str)
end , "::1", 8766)	-- bind an address
end
local function client_v6()
local c = socket.udp(function(str, from)
print("client_v6 recv", str, socket.udp_address(from))
end)
socket.udp_connect(c, "fe80::1", 8766)
for i=1,20 do …
```

1.提供支持ipv6的udp client和server接口, 可支持ipv6

---

HISTORY.md

I really enjoyed using this project, nice work! Caught a couple of typos in the HISTORY.md though 😛

Update HISTORY.md, fix typo(s)

---

lualib/skynet/db/redis/cluster.lua

fix(rediscluster): maybe too many connection when MOVED

---

skynet-src/skynet_monitor.c
skynet-src/skynet_server.c
skynet-src/skynet_socket.c
skynet-src/socket_server.c

统一 skynet_error 输出标准；异常日志 增加error tag

skynet_error output abnormal log add error tag

---

lualib/http/internal.lua

http client支持请求header里使用Transfer-Encoding: chunked

http chunked不能同时指定content-length

---

lualib/skynet/db/mongo.lua

mongo8.0 新增跨集合更新api: bulkWrite(相对单一更新 性能大幅提升)
btw: 低量级数据建议继续选择单一更新（insert/update等 ）
应用场景： 
1. 聚合数据更新
2. 日志db跨集合写入

feature: mongo 增加 bulkWrite

---

lualib-src/lua-bson.c

see https://github.com/cloudwu/skynet/discussions/2074

feature: add bson_to_lightuserdata api. see #2074
